(defun areaCuadrado( )
    (princ "Ingresa el lado del cuadrado: ")
    (setq lado (read))
    (format t "El area del cuadrado con lado ~A es igual a ~A.~%" lado (* lado lado))
)

(defun areaTriangulo ( )
    (format t "Ingresa la base del triangulo: ")
    (setq base (read))
    (format t "Ingresa la altura del triangulo: ")
    (setq altura (read))
    (format t "El area del triangulo es: ~A.~%" (/ (* base altura) 2))
)